### ISSUE TITLE
unable to download the setup exe

### ISSUE THREAD

**Issue by ibigpapa** [starlight/swan-desktop#30]
My company flagged the site as malware.
is there a way to compile it locally?

Also is there a way to use cygwin setup already on my machine to install?  I attempted to add the mirror `http://sirius.starlig.ht`  but it gave errors about the signature.

**Comment by lunchables** [comment]
There's already an issue open on this (#27).

**Comment by SharkWipf** [comment]
I don't think that issue is about the same problem.  
This issue isn't about Swan being detected as malware, but about not having access to the installer at all because of company policies.  
As for your question, @ibigpapa, I'm unable to tell you for sure but I think you can force the Cygwin installer to use extra repos through command line flags.  
It'd probably be easier to download it at home and install it from USB or upload it elsewhere though, that way you shouldn't have any of these issues.

**Comment by SharkWipf** [comment]
Have a look at these lines from the Swan installer, here it calls the Cygwin installer with the extra repo: [SwanSetup.nsi#L58-L63](https://github.com/starlight/swan-base/blob/master/SwanSetup.nsi#L58-L63).  
In theory running that on your existing Cygwin installer (changing the paths and whatnot of course) should allow you to install Swan with your Cygwin installer.

**Comment by isaacwhanson** [comment]
Another way to do it is to make sure you have `wget` installed in your existing cygwin and download the `spm` script from here:

https://raw.githubusercontent.com/starlight/swan-base/master/bin/spm

with that in your path, you can run `spm -i swan-desktop` to install (it will add the flags for you)
