### ISSUE TITLE
Swan suddenly changed home directory

### ISSUE THREAD

**Issue by tuhlmann** [starlight/swan-desktop#36]
I had installed Swan on a new Windows machine without any prior cygwin existence. I configured it and all worked fine. Configuration landed in %AppData%\Roaming\Swan

In addition I'm sometimes using ConEmu with the bash from the Swan installation (C:\Swan). That worked fine, but it seemed ConEmu did not use the AppData home directory but rather C:\Swan\home.

Now today, after quitting Swan and restarting it it suddenly reappeared with all changes lost, I had to reconfigure fonts, theme and every change I made.
I found out that the changes I made went into C:\Swan\home not into the %AppData% directory, although that is still there and the config still exists.

Where can I check and possible set the home directory Swan is using? In C:\Swan\etc\nsswitch.conf file everything is commented out (I did not change it).

Thanks,
Torsten.

**Comment by isaacwhanson** [comment]
Strange, I will definitely look tonight.. look in
/etc/profile.d/zz-userdirs.sh and 00-skel.sh

**Comment by SharkWipf** [comment]
You can run `cygpath -w "$HOME"` to see your current home directory on the Windows file system.  
Could it be you hadn't updated for a while, and only now got the home migration update? (see [this post](http://www.starlig.ht/2017/03/26/appdata/)).  
In the future, you should get notified of these changes after updating, but if you hadn't updated for a while you didn't have that functionality yet.

**Comment by tuhlmann** [comment]
I installed Swan on this machine 6 days ago (when I posted the first issue) which should be March 30th. It's close to when you changed the home folder but I believe I installed with the AppData home folder already in place- because that was the directory the settings originally went to, not the other way round as would have been if I migrated to the new settings.

Home seems to be:

```
tuhlmann@Archer ~$ cygpath.exe -w "$HOME"
C:\Swan\home\tuhlmann
```

I believe I found the problem (I'll verify in a bit). There's this snippet in `00-skel.sh`:

```
# mount AppData on $HOME
if ! mount | grep -i "home" >/dev/null; then
    mkdir -p "$(cygpath $APPDATA)/Swan"
    mount -fo user "${APPDATA}\\Swan" "$HOME"
fi
```
The only change I did yesterday, and now after reading this code I see the connection, is adding a new mount point to /etc/fstab. I wanted to mount the Windows home folder to, wait for it, `whome`. And that throws the above snippet off its feet. It finds a `home` in the list of mount points and thus does not mount to AppData.

Thanks for the right pointers to get me sort this out,
Torsten.

**Comment by SharkWipf** [comment]
Aah that explains it. Fair enough.
Shouldn't be hard to prevent that from happening, I'll submit a PR to fix
it once I'm a bit more awake.

Glad you managed to find the issue!


On Apr 5, 2017 10:03, "Torsten Uhlmann" <notifications@github.com> wrote:

I installed Swan on this machine 6 days ago (when I posted the first issue)
which should be March 30th. It's close to when you changed the home folder
but I believe I installed with the AppData home folder already in place-
because that was the directory the settings originally went to, not the
other way round as would have been if I migrated to the new settings.

Home seems to be:

tuhlmann@Archer ~$ cygpath.exe -w "$HOME"
C:\Swan\home\tuhlmann

I believe I found the problem (I'll verify in a bit). There's this snippet
in 00-skel.sh:

# mount AppData on $HOME
if ! mount | grep -i "home" >/dev/null; then
    mkdir -p "$(cygpath $APPDATA)/Swan"
    mount -fo user "${APPDATA}\\Swan" "$HOME"
fi

The only change I did yesterday, and now after reading this code I see the
connection, is adding a new mount point to /etc/fstab. I wanted to mount
the Windows home folder to, wait for it, whome. And that throws the above
snippet off its feet. It finds a home in the list of mount points and thus
does not mount to AppData.

Thanks for the right pointers to get me sort this out,
Torsten.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/starlight/swan-desktop/issues/36#issuecomment-291785163>,
or mute the thread

**Comment by tuhlmann** [comment]
I can confirm, after a restart and removing the `whome` mount point my home directory is back in AppData:

```
$ cygpath.exe -w "$HOME"
C:\Users\tuhlmann\AppData\Roaming\Swan
```

**Comment by SharkWipf** [comment]
This should be fixed if above PR gets merged: 
![image](https://cloud.githubusercontent.com/assets/751205/24757811/97025690-1ae0-11e7-8a3e-dacbf29cba82.png)

**Comment by isaacwhanson** [comment]
Thanks, @SharkWipf I will review it.

**Comment by isaacwhanson** [comment]
@SharkWipf 's fix has been merged.  It should make the system a bit more flexible.
