### ISSUE TITLE
Xfce pannel disappears after screen configuration change

### ISSUE THREAD

**Issue by jackluo923** [starlight/swan-desktop#41]
Xfce pannel disappears after screen configuration change. Currently, I use surface pro 3 as my main computer. When undocked, it uses the surface pro 3 screen. When docked into the docking station, it uses 3x1080P monitors. The xfce pannel disappears after screen configuration changes and there's no way to get it back without killing related processes or restart the computer. Simply relaunching the swane xfce4 desktop will prompt an error saying Cygwin/X A fatal error has occured and Cygwin/X will not exit. Server is already active for display 0. 

Is there a way to move the terminal icon to the task bar in the form or a toolbar or something along this line vs simply floating around? What is the proper way to relaunch the xfce pannel once it disappears?

**Comment by SharkWipf** [comment]
Sadly, I think this is a tricky one.  
Not speaking on behalf of @isaacwhanson here so their opinion might be different, but:  

The Xfce panel doesn't disappear, it's simply moved off-screen. This is also the reason why it'll complain when you try to start it again, it isn't closed, it's simply out of view.  
This is a problem with Windows, rather than Swan/Cygwin I think, and I doubt Swan will be able to work around this.  
Upstream Cygwin might be able to find a way around this, but that's way out of scope for Swan. You could try reporting a bug there.  
Normally you can "force" Windows to put all off-screen windows back on screen by right clicking the task bar and clicking "Cascade windows", but this doesn't work for floating always-on-top windows like the XFCE4 dock.  
Sadly, I think the best thing you can do to work around this is manually killing the "XWin.exe" process through task manager and restart Swan.  
> Is there a way to move the terminal icon to the task bar in the form or a toolbar or something along this line vs simply floating around?

I'm not sure actually, I do think there's an option to make the Xwin server appear in the tray area so you can more easily kill it, but I don't think you can move the XFCE4 panel to the task bar, as normally the XFCE4 panel, well, **is** the task bar.  
Again, maybe @isaacwhanson thinks differently about this so take my comment with a grain of salt.

**Comment by jackluo923** [comment]
Is there a way to launch x11 terminal via commandline without clicking the terminal button on the xfce panel?

**Comment by isaacwhanson** [comment]
to launch terminal from swan console, type:
`DISPLAY=:0 xfce4-terminal`
from there you should be able to run
`xfce4-logout`

**Comment by SharkWipf** [comment]
If you still have the panel running, you can launch the terminal using:  
From cmd.exe:  
```
bash -c 'DISPLAY=:0 xfce4-terminal'
```
Or from Swan console (should also be installed) just: 
```
DISPLAY=:0 xfce4-terminal &
```
You could throw the cmd.exe one in a .bat file and run that, do note that it won't fork though so it'll stay in the foreground. Haven't found a fix for that yet.  
@isaacwhanson I don't seem to have xfce4-logout on my install, although I'm a bit behind on updates. Is that included in the base packages?

**Comment by isaacwhanson** [comment]
maybe I typed that wrong, I am mobile at the moment. maybe it was `xfce4-session-logout`

**Comment by SharkWipf** [comment]
Yep, that's the one. Didn't know that command.  
That also means that you can simply close Swan by directly running:
```
bash -c 'DISPLAY=:0 xfce4-session-logout'
```
in cmd.exe or a .bat file.  
I experimented a bit with including that command in the startup shortcut, but sadly that seemed to cause different problems.  
At least this command provides a clean way to shut down Swan, less cumbersome than killing it through task manager at least.

**Comment by isaacwhanson** [comment]
may be good idea to create a `logout` script one could run from swan console too.  I don't know if I would want existing session killed if you start another. I do that accidently sometimes. maybe if there was a choice dialog that popped.

unfortunately I think the original display change issue can't be helped.

**Comment by jackluo923** [comment]
So I have figured out a clean way of doing this. It involves using tools such as script functions from DisplayFusion or autohotkey. 

I wrote couple lines of C# code which is triggered with a keyboard shortcut. When I need to use the xfce4-pannel, the code will move the panel to the correct location regardless of monitor configurations. 

using System;
using System.Drawing;
public static class DisplayFusionFunction
{
	public static void Run(IntPtr windowHandle)
	{
        // obtain window handler for xfce4-panel
        IntPtr xfce4PannelWindowHandler = BFS.Window.GetWindowByText("xfce4-panel");
        BFS.Window.Focus(xfce4PannelWindowHandler);
  
        // move the window to the appropriate location on the primary monitor's taskbar
        Rectangle bounds = BFS.Monitor.GetPrimaryMonitorBounds();        
        BFS.Window.SetLocation(xfce4PannelWindowHandler, bounds.Width-700, bounds.Height-38);
        
        // set always on top to false so it hides behind taskbar when not needed
        BFS.Window.SetAlwaysOnTop(xfce4PannelWindowHandler, false);
	}
}

The result is docked panel which only gets enabled with a shortcut. Otherwise, it spends the rest of the time hiding behind the semi-transparent windows 10 taskbar without affecting any workflow.
