### ISSUE TITLE
Volume keys support?

### ISSUE THREAD

**Issue by ivdok** [starlight/swan-desktop#5]
Right now Explorer handles interaction with them on Windows 10. Using Xfce as default shell (via group policy) means I can't trigger volume management without running Explorer. On Linux, xfce4-volumed handles volume keys. On Windows, this can be done using [waveOutSetVolume](https://msdn.microsoft.com/en-us/library/ms713762%28VS.85%29.aspx) API. Can it be reimplemented in scope of this project?

**Comment by isaacwhanson** [comment]
This is interesting.  I am going to need to do some research on this, and would appreciate any more information that you can provide.  I have questions!

- I assume you have installed the `lux-desktop-audio` package.  is that right?
- _"Xfce as default shell (via group policy)"_: could you elaborate? Are you not starting explorer.exe on login?
- How do you use this project? Starlight/lux is a new project and I am interested in what users want from a system.

I will look into the volume up/down key activation and see what I can do.  It may be that we need the `xfce4-volumed` compiled for cygwin and added to the package dependencies for `lux-desktop-audio`.  Or, maybe we need a keyboard mapping that triggers a win32 shell script via `cygstart`.

**Comment by ivdok** [comment]
1. No, I didn't. But is it needed? Because in my case I want to set level of Windows application, not Cygwin ones. Just curious.
2. No, I'm not. `gpedit.msc > User Configuration > Administrative > System > Custom User Interface`. Filled with X11 server call and Xfce, i.e. `C:\lux-x86_64\bin\run.exe --quote /usr/bin/bash.exe -l -c "cd; exec /usr/bin/startx /etc/X11/xinit/Xsession xfce"`
3. I use it as a "first resort": when Xfce launches on boot, I can startup resource hogs like Visual Studio or Fallout 4 without stutters and with minimal environment. I also did a shortcut which launches Explorer when needed.

**Comment by isaacwhanson** [comment]
1. No, it is not needed if you are just dealing with Windows apps.
lux-desktop-audio provides an audio system for Cygwin apps.
2/3. That is cool, I haven't tried that. I will give it a shot. Take a look
at the `cygstart` command. You can use that to launch Windows scripts (or
whatever) and then bind that comand to an Xfce keyboard shortcut.

Thanks for the info, I will look into this further
On May 29, 2016 1:10 PM, "ivdok" <notifications@github.com> wrote:


   1. No, I didn't. But is it needed? Because in my case I want to set
   level of Windows application, not Cygwin ones. Just curious.
   2. No, I'm not. gpedit.msc > User Configuration > Administrative >
   System > Custom User Interface. Filled with X11 server call and Xfce,
   i.e. C:\lux-x86_64\bin\run.exe --quote /usr/bin/bash.exe -l -c "cd; exec
   /usr/bin/startx /etc/X11/xinit/Xsession xfce"
   3. I use it as a "first resort": when Xfce launches on boot, I can
   startup resource hogs like Visual Studio or Fallout 4 without stutters and
   with minimal environment. I also did a shortcut which launches Explorer
   when needed.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/starlight/lux-desktop/issues/5#issuecomment-222371449>,
or mute the thread
<https://github.com/notifications/unsubscribe/AA3Z9_fbx72Dz3dSczIbPQx1bbWbX_6gks5qGch1gaJpZM4IpUiv>
.

**Comment by ivdok** [comment]
Further observations show that *-volumed depends on [libkeybinder](https://github.com/fd00/yacp/tree/master/keybinder) and GStreamer 0.10. Both are available at Cygwin, but gst-0.10 is considered deprecated on Linux. You've probably heard that in 4.12 Xfce announcement. Although GStreamer dependency is still at question, as I didn't inspect how it works under Windows.

**Comment by isaacwhanson** [comment]
So, libkeybinder is only going to work for applications hosted in the X server (not the Windows apps).  And xfce4-volumed will have the same limitation.  The same goes for all the Xfce keybindings, actually.  I don't see a viable solution, from a cygwin/xfce perspective.  This could work for apps using X display, but not the native apps.  I am going to mark this "won't fix", but I could revisit that if new information becomes available.

**Comment by SharkWipf** [comment]
Bit late to reply to this, but I think the WinAPI is your only viable option here.  
If you don't want to mess with an application that toys with the WinAPI you'd probably have to modify Cygwin's source itself. 

Some quick investigation into the WinAPI tells me it is a bit of a mess, and there's no clean way to access it from simple scripts, but there's a bunch of copy-pastable examples on StackOverflow that allow you to control Windows volume through IAudioEndpointVolume, mostly in C#.  

It may not be the cleanest solution, but it should be pretty reliable. Just configure it in the xfce4-keyboard-shortcuts.xml file and you should be set.  
On "native" Linux distros it's just as bad, if you use a window manager like i3, "hacky" stuff like this is the only way to get media keys working in the first place: 
```
bindsym XF86AudioRaiseVolume exec pulseaudio-ctl up 2
bindsym XF86AudioLowerVolume exec pulseaudio-ctl down 2
bindsym XF86AudioMute exec pulseaudio-ctl mute
```
