### ISSUE TITLE
Improve performance (on Windows 7)

### ISSUE THREAD

**Issue by zielot** [starlight/swan-desktop#53]
Hi folks,

Just got started using the Swan/XFCE desktop and the first thing I notice is that it is very slow on my machine - Windows 7 Professional running on i7 2.8 w 16Gb of ram. I just performed an informal timing of the XFCE desktop loading processing and got distracted after I had passed 240. I am guessing that this is a known issue. Is it only Windows 7 machines or is it a general issue? Is there anyway I can improve the performance?

I do think it's cool to be able to run a Linux desktop on an emulation layer so keep up the nice work folks!

**Comment by isaacwhanson** [comment]
Thanks for the feedback!  It is definitely slow starting-up.  I think this is mostly due to the implementation of the POSIX `fork()` system call in Cygwin.  I will see if I can do anything about it.

**Comment by SharkWipf** [comment]
Slow, yes, but 240 (seconds?) seems extreme. My i5 NUC starts up Swan in
~15-20 seconds.

We had someone else with a similar issue (#46) before, can you replicate
their results?


On Jan 16, 2018 19:38, "Isaac W Hanson" <notifications@github.com> wrote:

Thanks for the feedback! It is definitely slow starting-up. I think this is
mostly due to the implementation of the POSIX fork() system call in Cygwin.
I will see if I can do anything about it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/starlight/swan-desktop/issues/53#issuecomment-358062091>,
or mute the thread

**Comment by zielot** [comment]
I'll read through that thread and check it out.
