### ISSUE TITLE
Desktop management?

### ISSUE THREAD

**Issue by aubade** [starlight/swan-desktop#54]
It'd be really nice if Swan could replace windows' desktop icons, so that any folders or shortcuts there would open in thunar instead of explorer.

**Comment by isaacwhanson** [comment]
Generally, I have avoided integration from Windows -> Xfce (the other direction is prevalent).  This is because any functionality that requires the X server would not work when Xfce is not running (obviously).  Also, one of the principles of Swan is to make minimal changes to the Windows environment itself.  Often features like the one you describe require things like Windows Registry hacks (Swan makes ZERO registry changes).

I am willing to review any merge requests that implement this feature, without requiring windows system changes, such as to the registry, and will investigate whether this is possible otherwise.
